import esbuild from "esbuild";
import process from "process";
import { copyFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = "../vault/.obsidian/plugins/obsidian-agent";

const ctx = await esbuild.context({
  banner: { js: banner },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: ["obsidian"],
  format: "cjs",
  logLevel: "info",
  minify: prod,
  outfile: `${outdir}/main.js`,
  platform: "node",
  sourcemap: prod ? false : "inline",
  target: "ES2022",
  treeShaking: true,
});

await ctx.rebuild();

copyFileSync("styles.css", `${outdir}/styles.css`);
copyFileSync("manifest.json", `${outdir}/manifest.json`);
console.log("[ObsidianAgent:Build] manifest.json + styles.css copied to vault plugin dir");

if (prod) {
  await ctx.dispose();
} else {
  await ctx.watch();
  console.log("[ObsidianAgent:Build] watching for changes...");
}
